export const faqItems = [
  {
    summary: "How do I mint Random Walk NFTs?",
    detail:
      "You need a browser wallet such as MetaMask and enough ETH on Arbitrum to mint the next NFT. You can bridge to Arbitrum via Hop, the Arbitrum Bridge, or withdraw directly from an exchange that supports Arbitrum."
  },
  {
    summary: "How do I add Arbitrum to my wallet?",
    detail:
      "Most wallets detect Arbitrum automatically when you connect. If not, you can add it from your wallet settings or switch when prompted by the site."
  },
  {
    summary: "How many Random Walk NFTs will there be?",
    detail:
      "The mint price increases by roughly 0.1% after each mint, so supply growth slows dramatically over time. A few thousand minted NFTs is more plausible than a very large collection."
  },
  {
    summary: "Where does the ETH from minting go?",
    detail:
      "After there has not been a mint for 30 days, the last minter can withdraw half of all ETH spent on minting up to that point. The remaining half stays in the contract and continues to roll forward under the same mechanism."
  },
  {
    summary: "Are the contracts verified?",
    detail:
      "Yes. Both the NFT contract and the market contract are verified on Arbiscan."
  },
  {
    summary: "What is the marketplace fee?",
    detail: "The built-in marketplace charges 0% fees."
  },
  {
    summary: "How are the NFT images generated?",
    detail:
      "Each NFT starts with an on-chain seed generated by the contract. That seed drives a Python-based random walk to create both still images and videos."
  },
  {
    summary: "What is a random walk?",
    detail:
      "A random walk repeatedly takes steps in random directions. When you plot enough of those steps, the resulting paths create the distinctive forms seen in Random Walk NFTs."
  },
  {
    summary: "How are the colors generated?",
    detail:
      "Colors are produced by a random walk in color space while the spatial walk unfolds, so each NFT evolves both position and color over time."
  },
  {
    summary: "Does the creator have special privileges?",
    detail:
      "No. Once deployed, the creator has no special minting or withdrawal privileges and participates under the same rules as everyone else."
  }
] as const;
